on: 
  pull_request:
    branches: 
      - main
      - development


jobs:
  lint_code_base:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Lint Code Base
      uses: github/super-linter/slim@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: ${{ github.base_ref }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Lint podspec
      run: pod spec lint SmartVideo.podspec
